export const runtimeCoverageStatuses = ["planned", "executable", "deferred"] as const;

export type RuntimeCoverageStatus = (typeof runtimeCoverageStatuses)[number];

export const GAME__RUNTIME_COVERAGE = {
  "ability.activate": "executable",
  "ability.exhaust_for_resource": "executable",
  "ability.recycle_for_power": "executable",
  "ability.play_token": "executable",
  "timing.action": "executable",
  "timing.reaction": "executable",
  "timing.delayed": "executable",
  "trigger.on_play": "executable",
  "trigger.second_card_played": "executable",
  "trigger.conquer_battlefield": "executable",
  "trigger.conquer_source": "executable",
  "trigger.conquer": "executable",
  "trigger.hold_battlefield": "executable",
  "trigger.on_move": "executable",
  "trigger.on_death": "executable",
  "trigger.on_damage": "executable",
  "trigger.event": "executable",
  "trigger.end_of_turn": "executable",
  "trigger.beginning": "executable",
  "trigger.first_beginning": "executable",
  "condition.compare_numeric_value": "executable",
  "condition.state": "executable",
  "condition.turn_event_count": "executable",
  "condition.event_value": "executable",
  "condition.event_origin_source_location": "executable",
  "condition.effect_killed_target": "executable",
  "condition.non_token": "executable",
  "condition.unit_presence": "executable",
  "selector.unit": "executable",
  "selector.friendly_unit": "executable",
  "selector.enemy_unit": "executable",
  "selector.card": "executable",
  "selector.friendly_card": "executable",
  "selector.gear": "executable",
  "selector.battlefield": "executable",
  "action.draw_cards": "executable",
  "action.vision": "executable",
  "action.look": "executable",
  "action.recycle_top_cards": "executable",
  "action.order_top_cards": "executable",
  "action.reveal": "executable",
  "keyword.vision": "executable",
  "action.discard_cards": "executable",
  "action.ready_cards": "executable",
  "action.exhaust_cards": "executable",
  "action.channel_runes": "executable",
  "action.deal_damage": "executable",
  "action.draw_by_optional_cost": "executable",
  "action.channel_or_draw": "executable",
  "action.fight": "executable",
  "action.kill_unit": "executable",
  "action.kill_on_next_damage": "executable",
  "action.kill_permanent": "executable",
  "action.buff_unit": "executable",
  "action.banish_card": "executable",
  "action.take_extra_turn": "executable",
  "action.gain_points": "executable",
  "action.win_game": "executable",
  "action.stun_card": "executable",
  "action.return_to_hand": "executable",
  "action.take_to_hand": "executable",
  "action.recycle_cards": "executable",
  "action.move_unit": "executable",
  "action.play_token": "executable",
  "action.play_selected_unit": "executable",
  "modifier.modify_numeric_value": "executable",
  "modifier.play_unit_destination": "executable",
  "modifier.cannot_move_from_source_battlefield": "executable",
  "modifier.legion_energy_discount": "executable",
  "modifier.grant_keyword": "executable",
  "modifier.enter_ready": "executable",
  "trigger.attack": "executable",
  "trigger.defend": "executable",
  "trigger.defend_at_source_battlefield": "executable",
  "keyword.assault": "executable",
  "keyword.shield": "executable",
  "keyword.tank": "executable",
  "keyword.deflect": "executable",
  "keyword.ganking": "executable",
  "keyword.hidden": "executable",
  "keyword.accelerate": "executable",
  "keyword.legion": "executable",
  "cost.pay": "executable",
  "cost.exhaust_source": "executable",
  "cost.exhaust_selected_unit": "executable",
  "cost.spend_buff": "executable",
  "cost.spend_source_buff": "executable",
  "choice.optional": "executable",
  "choice.choose_mode": "executable",
  "keyword.temporary": "executable",
  "replacement.recall_on_next_death": "executable",
  "modifier.cannot_play_cards": "executable",
  "modifier.enable_source_triggers": "executable",
} as const satisfies Record<string, RuntimeCoverageStatus>;

export function getRuntimeCoverageStatus(
  behaviorId: string
): RuntimeCoverageStatus | null {
  return GAME__RUNTIME_COVERAGE[
    behaviorId as keyof typeof GAME__RUNTIME_COVERAGE
  ] ?? null;
}
