export const runtimeCoverageStatuses = ["planned", "executable", "deferred"] as const;

export type RuntimeCoverageStatus = (typeof runtimeCoverageStatuses)[number];

export const GAME__RUNTIME_COVERAGE = {
  "ability.exhaust_for_resource": "executable",
  "ability.recycle_for_power": "executable",
  "ability.equip": "executable",
  "ability.empower": "executable",
  "ability.activated_effect": "executable",
  "timing.action": "executable",
  "timing.reaction": "executable",
  "timing.delayed": "executable",
  "trigger.on_play": "executable",
  "trigger.conquer_battlefield": "executable",
  "trigger.conquer": "executable",
  "trigger.hold_battlefield": "executable",
  "trigger.hold": "executable",
  "trigger.on_move": "executable",
  "trigger.on_death": "executable",
  "trigger.friendly_unit_combat": "executable",
  "trigger.end_of_turn": "executable",
  "condition.compare_numeric_value": "executable",
  "condition.effect_killed_target": "executable",
  "condition.unit_presence": "executable",
  "condition.card_type_presence": "executable",
  "condition.event_subject_combat_alone": "executable",
  "selector.unit": "executable",
  "selector.friendly_unit": "executable",
  "selector.enemy_unit": "executable",
  "selector.move_destination": "executable",
  "selector.card": "executable",
  "selector.source": "executable",
  "selector.gear": "executable",
  "selector.battlefield": "executable",
  "selector.chain_item": "executable",
  "action.draw_cards": "executable",
  "action.draw_by_controlled_battlefield_count": "executable",
  "action.search_top_deck": "executable",
  "action.gain_xp": "executable",
  "action.reveal_opponent_hand": "executable",
  "action.grant_facedown_vision": "executable",
  "action.vision": "executable",
  "keyword.vision": "executable",
  "keyword.quick_draw": "executable",
  "keyword.hidden": "executable",
  "keyword.temporary": "executable",
  "type.additional": "executable",
  "action.discard_cards": "executable",
  "action.ready_cards": "executable",
  "action.channel_runes": "executable",
  "action.deal_damage": "executable",
  "action.draw_by_optional_cost": "executable",
  "action.channel_or_draw": "executable",
  "action.fight": "executable",
  "action.kill_unit": "executable",
  "action.kill_card": "executable",
  "action.counter_chain_item": "executable",
  "action.return_to_hand": "executable",
  "action.move_unit": "executable",
  "action.play_token": "executable",
  "action.attach_equipment": "executable",
  "action.detach_equipment": "executable",
  "action.optional": "executable",
  "modifier.modify_numeric_value": "executable",
  "modifier.play_unit_destination": "executable",
  "modifier.enter_ready": "executable",
  "modifier.ignore_deflect": "executable",
  "trigger.attack": "executable",
  "trigger.defend": "executable",
  "keyword.assault": "executable",
  "keyword.shield": "executable",
  "keyword.tank": "executable",
  "keyword.deflect": "executable",
  "keyword.ganking": "executable",
  "cost.exhaust_selected_unit": "executable",
  "cost.pay": "executable",
  "cost.exhaust_source": "executable",
  "replacement.recall_on_next_death": "executable",
} as const satisfies Record<string, RuntimeCoverageStatus>;

export function getRuntimeCoverageStatus(
  behaviorId: string
): RuntimeCoverageStatus | null {
  return GAME__RUNTIME_COVERAGE[
    behaviorId as keyof typeof GAME__RUNTIME_COVERAGE
  ] ?? null;
}
