export const runtimeCoverageStatuses = ["planned", "executable", "deferred"] as const;

export type RuntimeCoverageStatus = (typeof runtimeCoverageStatuses)[number];

export const GAME__RUNTIME_COVERAGE = {
  "ability.exhaust_for_resource": "executable",
  "ability.recycle_for_power": "executable",
  "timing.action": "executable",
  "timing.reaction": "executable",
  "timing.delayed": "executable",
  "trigger.on_play": "executable",
  "trigger.second_card_played": "executable",
  "trigger.conquer_battlefield": "executable",
  "trigger.conquer_source": "executable",
  "trigger.conquer": "executable",
  "trigger.hold_battlefield": "executable",
  "trigger.on_move": "executable",
  "trigger.on_death": "executable",
  "trigger.end_of_turn": "executable",
  "trigger.beginning": "executable",
  "condition.compare_numeric_value": "executable",
  "condition.effect_killed_target": "executable",
  "condition.unit_presence": "executable",
  "selector.unit": "executable",
  "selector.friendly_unit": "executable",
  "selector.enemy_unit": "executable",
  "selector.card": "executable",
  "selector.battlefield": "executable",
  "action.draw_cards": "executable",
  "action.vision": "executable",
  "action.look": "executable",
  "action.reveal": "executable",
  "keyword.vision": "executable",
  "action.discard_cards": "executable",
  "action.ready_cards": "executable",
  "action.exhaust_cards": "executable",
  "action.channel_runes": "executable",
  "action.deal_damage": "executable",
  "action.draw_by_optional_cost": "executable",
  "action.channel_or_draw": "executable",
  "action.fight": "executable",
  "action.kill_unit": "executable",
  "action.banish_card": "executable",
  "action.stun_card": "executable",
  "action.return_to_hand": "executable",
  "action.recycle_cards": "executable",
  "action.move_unit": "executable",
  "action.play_token": "executable",
  "modifier.modify_numeric_value": "executable",
  "modifier.play_unit_destination": "executable",
  "modifier.legion_energy_discount": "executable",
  "modifier.enter_ready": "executable",
  "trigger.attack": "executable",
  "trigger.defend": "executable",
  "keyword.assault": "executable",
  "keyword.shield": "executable",
  "keyword.tank": "executable",
  "keyword.deflect": "executable",
  "keyword.ganking": "executable",
  "keyword.accelerate": "executable",
  "keyword.legion": "executable",
  "cost.pay": "executable",
  "cost.exhaust_source": "executable",
  "cost.exhaust_selected_unit": "executable",
  "choice.optional": "executable",
  "keyword.temporary": "executable",
  "replacement.recall_on_next_death": "executable",
} as const satisfies Record<string, RuntimeCoverageStatus>;

export function getRuntimeCoverageStatus(
  behaviorId: string
): RuntimeCoverageStatus | null {
  return GAME__RUNTIME_COVERAGE[
    behaviorId as keyof typeof GAME__RUNTIME_COVERAGE
  ] ?? null;
}
